spring:
  application:
    name: core
  data:
    mongodb:
      uri: mongodb+srv://ecuTurismAdmin:d0Sqbwd7pHUSaYcF@ecuturism.6xd7tim.mongodb.net/planner
    redis:
      host: localhost
      port: 6379
      password: ""  # If Redis requires authentication, set the password
      timeout: 5s    # Connection timeout
      client-type: lettuce  # Use Lettuce as the Redis client
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
          max-wait: 5s
  mail:   # MailHog SMTP Configuration
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: false
          required: false
  messages:
    basename: messages
    encoding: UTF-8
server:
  port: 9000
  servlet:
    context-path: /api #api-base-ath

  # App Security
security:
  jwt:
    secret-key: ======================Lucky=Cat===========================
    expiration-time: 86400000
  #amazon-s3
aws:
  accessKey: AKIAZKDICYATTDBFA66W
  secretKey: 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
  bucketName: ec-turism-storage
  region: us-east-2
  #swagger

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  


  


