server:
  port: 8080
  servlet:
    context-path: /api  # API base path

spring:
  application:
    name: core

  data:
    mongodb:
      uri: ${PROD_MONGO_URI}

    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true

  mail:  # MailHog SMTP Configuration
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: false
          required: false

  messages:
    basename: messages
    encoding: UTF-8

security:
  jwt:
    secret-key: ${PROD_JWT_SECRET_KEY}
    expiration-time: 24  # In hours

aws:
  accessKey: ${PROD_AWS_ACCESSKEY}
  secretKey: ${PROD_AWS_SECRETKEY}
  bucketName: ${PROD_AWS_BUCKETNAME}
  region: ${PROD_AWS_REGION}